---
- name: block for copying locally
  block:
    - name: get the war file version
      shell: ls ./target/*.war
      register: war_version

    - name: copy the war file in appliation server
      copy:
              src: ./target/"{{ war_version }}"
              dest: /opt/tomcat/latest/webapps/
              owner: tomcat
              group: tomcat
              mode: 0777

  rescue:
    - name: download from artifact
      get_url:
        url: https://github.com/tejesh555/applogin/raw/master/target/applogin.war
        dest: /tmp

- name: copy artifact 
  copy:
     src: /tmp/applogin.war
     dest: /home/devops/workspace/CI-CD/applogin/target/applogin.war
     owner: tomcat
     group: tomcat
     remote_src: yes
  notify:
    - restart tomcat after deploy
  

