---
- name: copy the artifact from local to target machine
  copy:
     src: /home/devops/workspace/end_to_end/applogin/target/applogin-1.1.war
     dest: /tmp

- name: deploy the artifact to tomcat
  copy:
     src: /tmp/applogin-1.1.war
     dest: /opt/tomcat/latest/webapps/ 
     remote_src: yes
  notify:
    - restart tomcat
